export enum PERMISSIONS {
  // Student [cite: 147]
  VIEW_STUDENT = "VIEW_STUDENT",
  CREATE_STUDENT = "CREATE_STUDENT",
  EDIT_STUDENT = "EDIT_STUDENT",
  DELETE_STUDENT = "DELETE_STUDENT",

  // Class [cite: 148]
  VIEW_CLASS = "VIEW_CLASS",
  CREATE_CLASS = "CREATE_CLASS",
  EDIT_CLASS = "EDIT_CLASS",
  DELETE_CLASS = "DELETE_CLASS",

  // Attendance Setting [cite: 149]
  VIEW_ATTENDANCE_SETTING = "VIEW_ATTENDANCE_SETTING",
  MANAGE_ATTENDANCE_SETTING = "MANAGE_ATTENDANCE_SETTING",

  // Attendance [cite: 150]
  CHECKIN_ATTENDANCE = "CHECKIN_ATTENDANCE",
  CHECKOUT_ATTENDANCE = "CHECKOUT_ATTENDANCE",
  VIEW_ATTENDANCE = "VIEW_ATTENDANCE",
  MANAGE_ATTENDANCE = "MANAGE_ATTENDANCE",

  // Recap [cite: 151]
  VIEW_RECAP = "VIEW_RECAP",
  EXPORT_RECAP = "EXPORT_RECAP",
}
