import { UserRole } from "@prisma/client";
import { PERMISSIONS } from "../enum/permission.enum";

export const ROLE_PERMISSIONS: Record<UserRole, PERMISSIONS[]> = {
  ADMIN: Object.values(PERMISSIONS),
  STUDENT: [PERMISSIONS.VIEW_STUDENT, PERMISSIONS.CHECKIN_ATTENDANCE, PERMISSIONS.CHECKOUT_ATTENDANCE, PERMISSIONS.VIEW_ATTENDANCE, PERMISSIONS.VIEW_RECAP],
};
